# Generated by Django 5.2 on 2025-05-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='match',
            new_name='match_id',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='opponent_team',
            new_name='opponent_team_id',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='player',
            new_name='player_id',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='team',
            new_name='team_id',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='away_team',
            new_name='away_team_id',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='home_team',
            new_name='home_team_id',
        ),
        migrations.RenameField(
            model_name='standing',
            old_name='team',
            new_name='team_id',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='minute',
        ),
        migrations.RemoveField(
            model_name='standing',
            name='goals_conceded',
        ),
        migrations.RemoveField(
            model_name='standing',
            name='goals_scored',
        ),
        migrations.AddField(
            model_name='match',
            name='result',
            field=models.IntegerField(blank=True, choices=[(1, 'Home Win'), (2, 'Away Win'), (3, 'Draw')], null=True),
        ),
    ]
